// <auto-generated />
using System;
using HotelBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelBooking.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    partial class HotelBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Data.BookedDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("BookedDates");
                });

            modelBuilder.Entity("HotelBooking.Data.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HotelBooking.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeaturedImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "29 Rustaveli Ave, Tbilisi, Tbilisi, 0108",
                            City = "Tbilisi",
                            FeaturedImage = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/41cbdcb1.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "The Biltmore Hotel Tbilisi"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4, Freedom Square, Tbilisi, 0105",
                            City = "Tbilisi",
                            FeaturedImage = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/3e65a896.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "Courtyard by Marriott Tbilisi"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1 Republic square, Tbilisi, 0108",
                            City = "Tbilisi",
                            FeaturedImage = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/84d23097.jpg?impolicy=resizecrop&rw=1200&ra=fit",
                            Name = "Radisson Blu Iveria Hotel Tbilisi"
                        });
                });

            modelBuilder.Entity("HotelBooking.Data.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/78e5bc5d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 2,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/bf815e90.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 3,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/cbb31f78.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 4,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d9add37c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 5,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/11ed224a.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 6,
                            RoomId = 1,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/1f20a362.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 7,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/b6bb61fc.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 8,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/14b60598.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 9,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/99460f51.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 10,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/7aac5bc6.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 11,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/f7436d8f.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 12,
                            RoomId = 2,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d9add37c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 13,
                            RoomId = 3,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/74bb8203.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 14,
                            RoomId = 3,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/08619d53.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 15,
                            RoomId = 3,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/afdf2bac.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 16,
                            RoomId = 3,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/cbb31f78.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 17,
                            RoomId = 3,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d6ca6c86.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 18,
                            RoomId = 4,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/14b60598.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 19,
                            RoomId = 4,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/74bb8203.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 20,
                            RoomId = 4,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d6ca6c86.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 21,
                            RoomId = 4,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/78e5bc5d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 22,
                            RoomId = 4,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/8eb86ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 23,
                            RoomId = 5,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/cbb31f78.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 24,
                            RoomId = 5,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/bf815e90.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 25,
                            RoomId = 5,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/7aac5bc6.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 26,
                            RoomId = 5,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d6ca6c86.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 27,
                            RoomId = 6,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/14b60598.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 28,
                            RoomId = 6,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/f7436d8f.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 29,
                            RoomId = 6,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/99460f51.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 30,
                            RoomId = 6,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d9add37c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 31,
                            RoomId = 7,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/1f20a362.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 32,
                            RoomId = 7,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/11ed224a.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 33,
                            RoomId = 7,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/8eb86ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 34,
                            RoomId = 7,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d6ca6c86.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 35,
                            RoomId = 8,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/d6ca6c86.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 36,
                            RoomId = 8,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/854cc524.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 37,
                            RoomId = 8,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/1f20a362.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 38,
                            RoomId = 8,
                            Source = "https://images.trvl-media.com/lodging/16000000/15840000/15835100/15835033/3ac19564.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 39,
                            RoomId = 9,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 40,
                            RoomId = 9,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 41,
                            RoomId = 9,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/c3b4f65a.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 42,
                            RoomId = 9,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/8b412d08.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 43,
                            RoomId = 9,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/60315e6d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 44,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/d020b03c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 45,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/76e3960e.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 46,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 47,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 48,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/acd56094.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 49,
                            RoomId = 10,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/11f2b0fe.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 50,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/8715314f.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 51,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 52,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 53,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/1b7de5ef.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 54,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/9c55692c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 55,
                            RoomId = 11,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/11f2b0fe.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 56,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/58871759.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 57,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 58,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 59,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2ded8747.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 60,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/b437570e.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 61,
                            RoomId = 12,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/60315e6d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 62,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/ef867c3b.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 63,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 64,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 65,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/b437570e.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 66,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/60315e6d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 67,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/8b412d08.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 68,
                            RoomId = 13,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/ef867c3b.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 69,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/9c55692c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 70,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/2e585f43.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 71,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/eca80ca3.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 72,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/b437570e.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 73,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/60315e6d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 74,
                            RoomId = 14,
                            Source = "https://images.trvl-media.com/lodging/1000000/920000/916400/916376/8b412d08.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 75,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/ea540433.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 76,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/2b8b7804.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 77,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/26bab1f5.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 78,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/496c6b5a.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 79,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/2f36defd.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 80,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/ea540433.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 81,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/2b8b7804.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 82,
                            RoomId = 15,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/26bab1f5.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 83,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/406a3697.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 84,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/fa9c4653.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 85,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/14f420c8.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 86,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/c71aa3a5.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 87,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/549de7ab.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 88,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/a4557c21.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 89,
                            RoomId = 16,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/72dc8d9c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 90,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/10371176.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 91,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/549de7ab.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 92,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/c71aa3a5.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 93,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/16a596de.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 94,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/72dc8d9c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 95,
                            RoomId = 17,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/10371176.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 96,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/406a3697.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 97,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/67b0e7dc.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 98,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/549de7ab.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 99,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/95f52722.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 100,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/d3c76ffb.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 101,
                            RoomId = 18,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/715be0ff.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 102,
                            RoomId = 19,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/a2a0d8cd.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 103,
                            RoomId = 19,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/029d4d4c.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 104,
                            RoomId = 19,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/411ebc16.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 105,
                            RoomId = 19,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/d09117ce.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 106,
                            RoomId = 19,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/c9d0a60d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 107,
                            RoomId = 20,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/2b8b7804.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 108,
                            RoomId = 20,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/a263f2a2.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 109,
                            RoomId = 20,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/2056565d.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 110,
                            RoomId = 20,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/e498958a.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        },
                        new
                        {
                            Id = 111,
                            RoomId = 20,
                            Source = "https://images.trvl-media.com/lodging/3000000/2620000/2614700/2614694/4f130092.jpg?impolicy=fcrop&w=1200&h=800&p=1&q=medium"
                        });
                });

            modelBuilder.Entity("HotelBooking.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<int>("MaximumGuests")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerNight")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 3,
                            Name = "Premium Room",
                            PricePerNight = 199,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 3,
                            Name = "Deluxe Twin Room",
                            PricePerNight = 299,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 2,
                            Name = "Club Room",
                            PricePerNight = 89,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 5,
                            Name = "Deluxe Double Room",
                            PricePerNight = 189,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 3,
                            Name = "Junior Suite",
                            PricePerNight = 99,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 2,
                            Name = "Club Twin Room",
                            PricePerNight = 199,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 6,
                            Name = "Grand Deluxe Suite",
                            PricePerNight = 299,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            HotelId = 1,
                            MaximumGuests = 5,
                            Name = "Executive Suite",
                            PricePerNight = 299,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 5,
                            Name = "Superior Twin Room",
                            PricePerNight = 199,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 3,
                            Name = "Junior Suite",
                            PricePerNight = 99,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 5,
                            Name = "Superior Room",
                            PricePerNight = 399,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 3,
                            Name = "Executive Room",
                            PricePerNight = 99,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 13,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 4,
                            Name = "Deluxe Twin Room",
                            PricePerNight = 199,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 14,
                            Available = true,
                            HotelId = 2,
                            MaximumGuests = 3,
                            Name = "Deluxe Room",
                            PricePerNight = 149,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 4,
                            Name = "Premium Room",
                            PricePerNight = 149,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 16,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 6,
                            Name = "Superior Room",
                            PricePerNight = 299,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 3,
                            Name = "Superior Room, City View (High Floor)",
                            PricePerNight = 399,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 18,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 2,
                            Name = "Standard Room",
                            PricePerNight = 99,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 19,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 4,
                            Name = "Junior Suite",
                            PricePerNight = 199,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            Available = true,
                            HotelId = 3,
                            MaximumGuests = 2,
                            Name = "Premium Room",
                            PricePerNight = 149,
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("HotelBooking.Data.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Single Room"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Double Room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Deluxe Room"
                        });
                });

            modelBuilder.Entity("HotelBooking.Data.BookedDate", b =>
                {
                    b.HasOne("HotelBooking.Data.Room", null)
                        .WithMany("BookedDates")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Data.Image", b =>
                {
                    b.HasOne("HotelBooking.Data.Room", null)
                        .WithMany("Images")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Data.Room", b =>
                {
                    b.HasOne("HotelBooking.Data.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelBooking.Data.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("HotelBooking.Data.Room", b =>
                {
                    b.Navigation("BookedDates");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
